[project]
name = "chat-with-mcp"
version = "1.0.0"
description = "使用chainlit搭建的ai-chat，并支持自定义配置sse类型的MCP。"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.5.5",
    "fastmcp>=2.9.2",
    "openai>=1.92.2",
]
